import { Equipment, Review, Recommendation, UserNotification } from "@/types";

export const CATEGORIES = [
  {
    id: "Tractor",
    name: "Tractor",
    nameHi: "ट्रैक्टर",
    description: "Multi-purpose 30HP–75HP tractors for plowing, haulage, puddling & seeding.",
    descriptionHi: "जुताई, ढुलाई और बुवाई के लिए 30HP से 75HP ट्रैक्टर।",
    count: 320,
    image: "https://images.unsplash.com/photo-1592982537447-6f2a6a0c5c1c?auto=format&fit=crop&w=600&q=80",
    badge: "Most Booked"
  },
  {
    id: "Harvester",
    name: "Harvester",
    nameHi: "कंबाइन हार्वेस्टर",
    description: "Self-propelled multi-crop combine harvesters for wheat, paddy & soybean.",
    descriptionHi: "गेहूं, धान और सोयाबीन की त्वरित कटाई हेतु कंबाइन हार्वेस्टर।",
    count: 95,
    image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=600&q=80",
    badge: "Seasonal Peak"
  },
  {
    id: "Rotavator",
    name: "Rotavator",
    nameHi: "रोटावेटर",
    description: "High-speed rotary tillers for pulverizing soil & preparing fine seed beds.",
    descriptionHi: "मिट्टी को भुरभुरा और समतल बनाने के लिए 5 से 8 फीट रोटावेटर।",
    count: 180,
    image: "https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=600&q=80",
    badge: "Popular"
  },
  {
    id: "Seed Drill",
    name: "Seed Drill",
    nameHi: "सीड ड्रिल / हैप्पी सीडर",
    description: "Precision multi-crop zero till seeders & happy seeders for uniform sowing.",
    descriptionHi: "धान के अवशेषों में बिना जलाए गेहूं की सटीक बुवाई मशीन।",
    count: 110,
    image: "https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=600&q=80",
    badge: "Eco-Friendly"
  },
  {
    id: "Sprayer",
    name: "Sprayer",
    nameHi: "बूम / पावर स्प्रेयर",
    description: "Tractor-mounted 400L–1000L boom sprayers & high-pressure mist blowers.",
    descriptionHi: "बड़े खेतों में कीटनाशक और पोषण छिड़काव के लिए बूम स्प्रेयर।",
    count: 85,
    image: "https://images.unsplash.com/photo-1586771107445-d3ca888129ff?auto=format&fit=crop&w=600&q=80",
    badge: "High Demand"
  },
  {
    id: "Irrigation Equipment",
    name: "Irrigation Equipment",
    nameHi: "सिंचाई उपकरण व पंप",
    description: "Mobile diesel pump sets, rain guns, drip reels & portable HDPE pipes.",
    descriptionHi: "आपातकालीन जल आपूर्ति और छिड़काव के लिए पोर्टेबल डीजल पंप।",
    count: 140,
    image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80",
    badge: "Essential"
  },
  {
    id: "Thresher",
    name: "Thresher",
    nameHi: "मल्टीक्रॉप थ्रेशर",
    description: "Heavy-duty multi-crop threshers with elevator blowers for grain separation.",
    descriptionHi: "अनाज की 99% सफाई और बिना टूटन के गहाई के लिए थ्रेशर।",
    count: 75,
    image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=600&q=80",
    badge: "Post-Harvest"
  },
  {
    id: "Cultivator",
    name: "Cultivator",
    nameHi: "कल्टीवेटर",
    description: "Spring-loaded 9-tyne & 11-tyne cultivators for secondary tilling & weeding.",
    descriptionHi: "खरपतवार निकालने और मिट्टी को हवादार बनाने के लिए 9-टाइन कल्टीवेटर।",
    count: 165,
    image: "https://images.unsplash.com/photo-1592982537447-6f2a6a0c5c1c?auto=format&fit=crop&w=600&q=80",
    badge: "Standard"
  }
];

export const MOCK_EQUIPMENT: Equipment[] = [
  {
    id: "eq_tractor_01",
    owner_id: "usr_owner_01",
    owner_name: "Gurpreet Singh Gill",
    owner_phone: "+91 98765 43210",
    title: "Mahindra 575 DI Sarpanch 47 HP Tractor",
    category: "Tractor",
    brand: "Mahindra",
    model: "575 DI XP Plus",
    year: 2023,
    hp: 47,
    fuel_type: "Diesel",
    description: "High-torque 4-cylinder engine with dual clutch, power steering and rear hitch hydraulics. Complete with heavy haulage trolley and cage wheels for wet fields.",
    images: [
      "https://images.unsplash.com/photo-1592982537447-6f2a6a0c5c1c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80"
    ],
    hourly_rate: 450,
    daily_rate: 3200,
    security_deposit: 2500,
    with_driver: true,
    city: "Ludhiana",
    state: "Punjab",
    pincode: "141001",
    latitude: 30.901,
    longitude: 75.8573,
    is_available: true,
    condition: "Excellent",
    average_rating: 4.9,
    total_reviews: 38,
    total_bookings: 64,
    distance_km: 2.8
  },
  {
    id: "eq_tractor_02",
    owner_id: "usr_owner_02",
    owner_name: "Rameshwar Patel",
    owner_phone: "+91 98234 56789",
    title: "John Deere 5310 PowerTech 55 HP 4WD",
    category: "Tractor",
    brand: "John Deere",
    model: "5310 GearPro 4WD",
    year: 2024,
    hp: 55,
    fuel_type: "Diesel",
    description: "Heavy-duty 4-Wheel Drive tractor designed for tough field conditions, laser leveling, and heavy rotavator operations. Includes trained operator.",
    images: [
      "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1592982537447-6f2a6a0c5c1c?auto=format&fit=crop&w=800&q=80"
    ],
    hourly_rate: 600,
    daily_rate: 4200,
    security_deposit: 3500,
    with_driver: true,
    city: "Karnal",
    state: "Haryana",
    pincode: "132001",
    latitude: 29.6857,
    longitude: 76.9905,
    is_available: true,
    condition: "Like New",
    average_rating: 4.95,
    total_reviews: 52,
    total_bookings: 89,
    distance_km: 4.5
  },
  {
    id: "eq_rotavator_01",
    owner_id: "usr_owner_03",
    owner_name: "Balwant Yadav",
    owner_phone: "+91 97123 45678",
    title: "Shaktiman Semi-Champion 7 Feet Rotavator",
    category: "Rotavator",
    brand: "Shaktiman",
    model: "Semi-Champion 84 Inch",
    year: 2023,
    hp: 50,
    fuel_type: "PTO Driven",
    description: "Heavy-duty 54-blade rotary tiller for fine soil preparation in a single pass. Saves up to 35% fuel and ensures uniform seed bed preparation.",
    images: [
      "https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=800&q=80"
    ],
    hourly_rate: 350,
    daily_rate: 2200,
    security_deposit: 1500,
    with_driver: false,
    city: "Meerut",
    state: "Uttar Pradesh",
    pincode: "250001",
    latitude: 28.9845,
    longitude: 77.7064,
    is_available: true,
    condition: "Excellent",
    average_rating: 4.8,
    total_reviews: 23,
    total_bookings: 41,
    distance_km: 5.2
  },
  {
    id: "eq_harvester_01",
    owner_id: "usr_owner_01",
    owner_name: "Gurpreet Singh Gill",
    owner_phone: "+91 98765 43210",
    title: "Preet 987 Combine Harvester with SMS",
    category: "Harvester",
    brand: "Preet",
    model: "987 Super Deluxe",
    year: 2023,
    hp: 101,
    fuel_type: "Diesel",
    description: "Multi-crop combine harvester equipped with heavy cutter bar, straw management system (SMS), and clean grain tank. Best for wheat, paddy, and soybean.",
    images: [
      "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=800&q=80"
    ],
    hourly_rate: 1800,
    daily_rate: 14000,
    security_deposit: 10000,
    with_driver: true,
    city: "Ludhiana",
    state: "Punjab",
    pincode: "141001",
    latitude: 30.91,
    longitude: 75.845,
    is_available: true,
    condition: "Excellent",
    average_rating: 4.88,
    total_reviews: 31,
    total_bookings: 47,
    distance_km: 7.1
  },
  {
    id: "eq_seeddrill_01",
    owner_id: "usr_owner_04",
    owner_name: "Sukhdev Verma",
    owner_phone: "+91 94567 89012",
    title: "National Happy Seeder 11 Tyne (Zero Till)",
    category: "Seed Drill",
    brand: "National",
    model: "Eco-Seeder 11-Tyne",
    year: 2024,
    hp: 55,
    fuel_type: "PTO Driven",
    description: "Zero-till wheat sowing machine in standing paddy stubble. Eliminates stubble burning, preserves soil moisture, and achieves uniform germination.",
    images: [
      "https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=800&q=80"
    ],
    hourly_rate: 400,
    daily_rate: 2800,
    security_deposit: 2000,
    with_driver: true,
    city: "Patiala",
    state: "Punjab",
    pincode: "147001",
    latitude: 30.3398,
    longitude: 76.3869,
    is_available: true,
    condition: "Like New",
    average_rating: 4.92,
    total_reviews: 18,
    total_bookings: 29,
    distance_km: 8.4
  },
  {
    id: "eq_sprayer_01",
    owner_id: "usr_owner_05",
    owner_name: "Vikram Deshmukh",
    owner_phone: "+91 93712 34567",
    title: "Aspee Tractor Mounted 600L Boom Sprayer",
    category: "Sprayer",
    brand: "Aspee",
    model: "HTP-600 Turbo",
    year: 2023,
    hp: 35,
    fuel_type: "PTO Driven",
    description: "600-liter tractor-mounted boom sprayer with 12m swath width. Features ceramic nozzles for uniform pesticide and nutrient application across large acreage.",
    images: [
      "https://images.unsplash.com/photo-1586771107445-d3ca888129ff?auto=format&fit=crop&w=800&q=80"
    ],
    hourly_rate: 300,
    daily_rate: 2100,
    security_deposit: 1500,
    with_driver: true,
    city: "Nashik",
    state: "Maharashtra",
    pincode: "422001",
    latitude: 19.9975,
    longitude: 73.7898,
    is_available: true,
    condition: "Excellent",
    average_rating: 4.79,
    total_reviews: 26,
    total_bookings: 51,
    distance_km: 3.1
  },
  {
    id: "eq_irrigation_01",
    owner_id: "usr_owner_03",
    owner_name: "Balwant Yadav",
    owner_phone: "+91 97123 45678",
    title: "Kirloskar 10 HP Mobile Diesel Irrigation Pump",
    category: "Irrigation Equipment",
    brand: "Kirloskar",
    model: "Jalraj 10HP Mobile",
    year: 2022,
    hp: 10,
    fuel_type: "Diesel",
    description: "High-head portable diesel water pump mounted on a trolley with 150-meter delivery pipe and sprinkler heads. Perfect for emergency canal and borewell lifting.",
    images: [
      "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80"
    ],
    hourly_rate: 200,
    daily_rate: 1400,
    security_deposit: 1000,
    with_driver: false,
    city: "Meerut",
    state: "Uttar Pradesh",
    pincode: "250001",
    latitude: 28.98,
    longitude: 77.71,
    is_available: true,
    condition: "Good",
    average_rating: 4.65,
    total_reviews: 15,
    total_bookings: 24,
    distance_km: 6.2
  },
  {
    id: "eq_thresher_01",
    owner_id: "usr_owner_02",
    owner_name: "Rameshwar Patel",
    owner_phone: "+91 98234 56789",
    title: "Bhartiya Multi-Crop Thresher with Elevator",
    category: "Thresher",
    brand: "Bhartiya",
    model: "Super Delux 40 HP",
    year: 2023,
    hp: 40,
    fuel_type: "PTO Driven",
    description: "High output multi-crop thresher for wheat, mustard, grams, and pulses. High capacity blower ensures 99.8% grain cleanliness without seed breakage.",
    images: [
      "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=800&q=80"
    ],
    hourly_rate: 500,
    daily_rate: 3500,
    security_deposit: 2500,
    with_driver: true,
    city: "Karnal",
    state: "Haryana",
    pincode: "132001",
    latitude: 29.69,
    longitude: 76.98,
    is_available: true,
    condition: "Excellent",
    average_rating: 4.82,
    total_reviews: 34,
    total_bookings: 58,
    distance_km: 4.9
  },
  {
    id: "eq_cultivator_01",
    owner_id: "usr_owner_04",
    owner_name: "Sukhdev Verma",
    owner_phone: "+91 94567 89012",
    title: "Fieldking Spring Loaded 9-Tyne Cultivator",
    category: "Cultivator",
    brand: "Fieldking",
    model: "Heavy Duty 9 Tyne",
    year: 2023,
    hp: 40,
    fuel_type: "Tractor Mounted",
    description: "Spring-loaded tynes capable of aerating hard soil and uprooting weed roots up to 9 inches deep. High-grade boron steel shovel points.",
    images: [
      "https://images.unsplash.com/photo-1592982537447-6f2a6a0c5c1c?auto=format&fit=crop&w=800&q=80"
    ],
    hourly_rate: 250,
    daily_rate: 1600,
    security_deposit: 1200,
    with_driver: false,
    city: "Patiala",
    state: "Punjab",
    pincode: "147001",
    latitude: 30.345,
    longitude: 76.39,
    is_available: true,
    condition: "Excellent",
    average_rating: 4.8,
    total_reviews: 12,
    total_bookings: 21,
    distance_km: 8.1
  }
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev_01",
    booking_id: "bk_01",
    equipment_id: "eq_tractor_01",
    farmer_id: "usr_farmer_01",
    farmer_name: "Rajesh Kumar Sharma",
    farmer_location: "Village Samrala, Ludhiana",
    rating: 5,
    comment: "Tractor reached my farm right at 7:00 AM as promised. Driver Jagjit ji is very experienced. Ploughed my 6 acres smoothly with minimum fuel consumption. Transparent billing through FarmRentHub.",
    equipment_condition_rating: 5,
    owner_behavior_rating: 5,
    created_at: "2 days ago"
  },
  {
    id: "rev_02",
    booking_id: "bk_02",
    equipment_id: "eq_tractor_02",
    farmer_id: "usr_farmer_02",
    farmer_name: "Manjeet Singh Sandhu",
    farmer_location: "Karnal, Haryana",
    rating: 5,
    comment: "The John Deere 4WD performed flawlessly on our heavy black clay soil. We completed laser levelling in record time. No hidden charges and owner was very cooperative.",
    equipment_condition_rating: 5,
    owner_behavior_rating: 5,
    created_at: "5 days ago"
  },
  {
    id: "rev_03",
    booking_id: "bk_03",
    equipment_id: "eq_rotavator_01",
    farmer_id: "usr_farmer_03",
    farmer_name: "Satish Chand Tyagi",
    farmer_location: "Meerut, Uttar Pradesh",
    rating: 5,
    comment: "Shaktiman rotavator blades were sharp and brand new. Saved 2 passes of regular cultivator. Soil was pulverized to powder tilth. Will definitely rent again next season.",
    equipment_condition_rating: 5,
    owner_behavior_rating: 4,
    created_at: "1 week ago"
  },
  {
    id: "rev_04",
    booking_id: "bk_04",
    equipment_id: "eq_seeddrill_01",
    farmer_id: "usr_farmer_04",
    farmer_name: "Harbhajan Gill",
    farmer_location: "Patiala, Punjab",
    rating: 5,
    comment: "Happy Seeder saved us from burning crop residue. We sowed wheat directly into paddy straw. Sowing depth was uniform across all rows. Outstanding initiative by FarmRentHub.",
    equipment_condition_rating: 5,
    owner_behavior_rating: 5,
    created_at: "2 weeks ago"
  }
];

export const MOCK_RECOMMENDATIONS: Recommendation[] = [
  {
    equipment_id: "eq_tractor_01",
    title: "Mahindra 575 DI Sarpanch 47 HP",
    category: "Tractor",
    brand: "Mahindra",
    model: "575 DI XP Plus",
    daily_rate: 3200,
    hourly_rate: 450,
    average_rating: 4.9,
    distance_km: 2.8,
    image_url: "https://images.unsplash.com/photo-1592982537447-6f2a6a0c5c1c?auto=format&fit=crop&w=600&q=80",
    match_score: 98,
    recommended_reason: "Best fuel economy for 3–8 acre seedbed preparation this Rabi season.",
    best_for_crop: "Wheat, Mustard & Gram"
  },
  {
    equipment_id: "eq_rotavator_01",
    title: "Shaktiman Semi-Champion 7 Feet Rotavator",
    category: "Rotavator",
    brand: "Shaktiman",
    model: "Semi-Champion 84 Inch",
    daily_rate: 2200,
    hourly_rate: 350,
    average_rating: 4.8,
    distance_km: 5.2,
    image_url: "https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=600&q=80",
    match_score: 94,
    recommended_reason: "Single-pass seedbed preparation reduces tractor operational hours by 35%.",
    best_for_crop: "Wheat, Potato & Vegetables"
  },
  {
    equipment_id: "eq_seeddrill_01",
    title: "National Happy Seeder 11 Tyne (Zero Till)",
    category: "Seed Drill",
    brand: "National",
    model: "Eco-Seeder 11-Tyne",
    daily_rate: 2800,
    hourly_rate: 400,
    average_rating: 4.92,
    distance_km: 8.4,
    image_url: "https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=600&q=80",
    match_score: 91,
    recommended_reason: "Direct drilling in paddy straw eliminates stubble management expenses.",
    best_for_crop: "Wheat Direct Seeding"
  }
];

export const MOCK_NOTIFICATIONS: UserNotification[] = [
  {
    id: "notif_01",
    title: "Booking Confirmed",
    message: "Your booking for Mahindra 575 DI Tractor (#FRH-7821) is confirmed for tomorrow 8:00 AM.",
    type: "booking",
    time: "10 mins ago",
    read: false
  },
  {
    id: "notif_02",
    title: "Payment Received",
    message: "Security deposit of ₹2,500 safely held in escrow. Refund processed automatically on return.",
    type: "payment",
    time: "25 mins ago",
    read: false
  },
  {
    id: "notif_03",
    title: "Rental Reminder",
    message: "Driver Jagjit (+91 98765 43210) has left owner's garage and will arrive in 40 minutes.",
    type: "reminder",
    time: "1 hour ago",
    read: true
  },
  {
    id: "notif_04",
    title: "Owner Availability Update",
    message: "Preet 987 Harvester is now open for bookings in Ludhiana & Khanna clusters.",
    type: "availability",
    time: "3 hours ago",
    read: true
  }
];

export const HOW_IT_WORKS_STEPS = [
  {
    step: "01",
    title: "Choose Equipment",
    titleHi: "उपकरण चुनें",
    desc: "Browse tractors, harvesters, rotavators and seeders with complete technical specs, rates, and genuine field photos.",
    descHi: "अपनी खेती की जरूरत के अनुसार ट्रैक्टर, हार्वेस्टर या रोटावेटर चुनें।"
  },
  {
    step: "02",
    title: "Find Nearby Owners",
    titleHi: "नजदीकी मालिक खोजें",
    desc: "Locate verified machinery owners within your panchayat or block radius to minimize haulage time and delivery fee.",
    descHi: "अपने गांव या तहसील के पास सत्यापित मशीन मालिकों को खोजें।"
  },
  {
    step: "03",
    title: "Check Availability",
    titleHi: "उपलब्धता जांचें",
    desc: "Select your sowing or harvesting dates and check live machine calendar slots with hourly or full-day booking.",
    descHi: "अपनी सुविधानुसार दिन या घंटे चुनें और लाइव स्लॉट देखें।"
  },
  {
    step: "04",
    title: "Book & Rent",
    titleHi: "बुक करें और काम शुरू करें",
    desc: "Confirm with secure UPI/Card escrow payment. Machine arrives at your farm field with an experienced operator.",
    descHi: "सुरक्षित भुगतान करें। मशीन आपके खेत पर काम के लिए समय पर पहुंचेगी।"
  }
];
